# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mensageria_pb2 as mensageria__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mensageria_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MensageriaServiceStub(object):
    """Serviço que define o envio de mensagens
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnviarMensagem = channel.unary_unary(
                '/mensageria.MensageriaService/EnviarMensagem',
                request_serializer=mensageria__pb2.MensagemRequest.SerializeToString,
                response_deserializer=mensageria__pb2.MensagemResponse.FromString,
                _registered_method=True)


class MensageriaServiceServicer(object):
    """Serviço que define o envio de mensagens
    """

    def EnviarMensagem(self, request, context):
        """Envia uma mensagem e retorna uma confirmação
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MensageriaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnviarMensagem': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarMensagem,
                    request_deserializer=mensageria__pb2.MensagemRequest.FromString,
                    response_serializer=mensageria__pb2.MensagemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mensageria.MensageriaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mensageria.MensageriaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MensageriaService(object):
    """Serviço que define o envio de mensagens
    """

    @staticmethod
    def EnviarMensagem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mensageria.MensageriaService/EnviarMensagem',
            mensageria__pb2.MensagemRequest.SerializeToString,
            mensageria__pb2.MensagemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
