# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mensageria.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'mensageria.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10mensageria.proto\x12\nmensageria\"9\n\x0fMensagemRequest\x12\x10\n\x08mensagem\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x65stinatario\x18\x02 \x01(\t\"\"\n\x10MensagemResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2b\n\x11MensageriaService\x12M\n\x0e\x45nviarMensagem\x12\x1b.mensageria.MensagemRequest\x1a\x1c.mensageria.MensagemResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mensageria_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MENSAGEMREQUEST']._serialized_start=32
  _globals['_MENSAGEMREQUEST']._serialized_end=89
  _globals['_MENSAGEMRESPONSE']._serialized_start=91
  _globals['_MENSAGEMRESPONSE']._serialized_end=125
  _globals['_MENSAGERIASERVICE']._serialized_start=127
  _globals['_MENSAGERIASERVICE']._serialized_end=225
# @@protoc_insertion_point(module_scope)
